baseurl: 'https://rudnkh.me'
title: 'rudnkh'
minify:
  minifyOutput: true
publishDir: 'docs'
permalinks:
  notes: /notes/:contentbasename/
  playing: /playing/:contentbasename/
  writeups: /writeups/:contentbasename/
  watching: /watching/:contentbasename/
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
params:
  cdn: '/images/'
