baseurl: 'https://rudnkh.me'
minify: false
publishDir: 'docs'
permalinks:
  notes: /notes/:filename/
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
params:
  cdn: 'https://cdn.rudnkh.me/'
